nodejs:
  applicationPort: 1337
  image: 'hmctspublic.azurecr.io/crumble/frontend:latest'
  aadIdentityName: cnp
  environment:
    RECIPE_BACKEND_URL: http://plum-recipe-backend-java
  keyVaults:
    "crumblesi":
      secrets:
        - name: appInsights-InstrumentationKey