name: plum-frontend
apiVersion: v2
home: https://github.com/hmcts/cnp-plum-frontend
version: 0.1.13
description: HMCTS Plum frontend application (test application)
maintainers:
  - name: HMCTS Platform Engineering Team
dependencies:
  - name: nodejs
    version: 2.4.5
    repository: "https://hmctspublic.azurecr.io/helm/v1/repo/"
  - name: elasticsearch
    version: 7.8.3
    repository: '@hmctspublic'
    #condition: ccd.elastic.enabled
