nodejs:
  applicationPort: 1337
  image: 'hmctspublic.azurecr.io/plum/frontend:latest'
  ingressHost: plum-recipe-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: cnp
  environment:
    # test webhook
    RECIPE_BACKEND_URL: http://plum-recipe-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    'plumsi':
      secrets:
        - name: appInsights-InstrumentationKey
